name: test_ci

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on:  ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - uses: docker/login-action@v1
        name: login dockerhub
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: docker/setup-buildx-action@v1
        name: docker build
        id: buildx

      - uses: docker/build-push-action@v2
        name: docker build push tag
        id: docker_build
        with:
          context: ./test_ci
          file: ./dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags : ${{ secrets.DOCKER_USERNAME }}/docker_pro

      - name: vertify
        run: echo ${{ steps.docker_build.outputs.digest }}

     